{
	"id": "CVE-1999-0846",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Modified",
	"published": "1999-12-01T05:00:00.000",
	"lastModified": "2022-08-17T06:15:21.813",
	"descriptions": [
		{
			"lang": "en",
			"value": "Denial of service in MDaemon 2.7 via a large number of connection attempts."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"url": "https://marc.info/?l=bugtraq&m=94398020817351&w=2"
		}
	],
	"metrics": {
		"cvssMetricV2": [
			{
				"source": "nvd@nist.gov",
				"type": "Primary",
				"cvssData": {
					"version": "2.0",
					"vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
					"accessVector": "NETWORK",
					"accessComplexity": "LOW",
					"authentication": "NONE",
					"confidentialityImpact": "NONE",
					"integrityImpact": "NONE",
					"availabilityImpact": "PARTIAL",
					"baseScore": 5
				},
				"baseSeverity": "MEDIUM",
				"exploitabilityScore": 10,
				"impactScore": 2.9
			}
		]
	},
	"weaknesses": [
		{
			"source": "nvd@nist.gov",
			"type": "Primary",
			"description": [
				{
					"lang": "en",
					"value": "NVD-CWE-Other"
				}
			]
		}
	],
	"configurations": [
		{
			"nodes": [
				{
					"operator": "OR",
					"cpeMatch": [
						{
							"vulnerable": true,
							"criteria": "cpe:2.3:a:deerfield:mdaemon:2.8.5:*:*:*:*:*:*:*",
							"matchCriteriaId": "189DC153-488F-496B-A807-7E3F8AC815C4"
						},
						{
							"vulnerable": true,
							"criteria": "cpe:2.3:a:deerfield:mdaemon:2.8.6:*:*:*:*:*:*:*",
							"matchCriteriaId": "B7E862B7-F01C-44B5-A0F6-FF0C6DDD5C9F"
						}
					]
				}
			]
		}
	]
}
