{
	"id": "CVE-2025-0158",
	"sourceIdentifier": "psirt@us.ibm.com",
	"vulnStatus": "Awaiting Analysis",
	"published": "2025-02-06T21:15:21.923",
	"lastModified": "2025-02-06T21:15:21.923",
	"descriptions": [
		{
			"lang": "en",
			"value": "IBM EntireX 11.1 could allow a local user to cause a denial of service due to an unhandled error and fault isolation."
		},
		{
			"lang": "es",
			"value": "IBM EntireX 11.1 podría permitir que un usuario local provoque una denegación de servicio debido a un error no controlado y un aislamiento de falla."
		}
	],
	"references": [
		{
			"source": "psirt@us.ibm.com",
			"url": "https://www.ibm.com/support/pages/node/7182693"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "psirt@us.ibm.com",
				"type": "Primary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
					"attackVector": "LOCAL",
					"attackComplexity": "LOW",
					"privilegesRequired": "LOW",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "NONE",
					"availabilityImpact": "HIGH",
					"baseScore": 5.5,
					"baseSeverity": "MEDIUM"
				},
				"exploitabilityScore": 1.8,
				"impactScore": 3.6
			}
		]
	},
	"weaknesses": [
		{
			"source": "psirt@us.ibm.com",
			"type": "Primary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-248"
				}
			]
		}
	]
}
