{
	"id": "CVE-2024-28732",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Awaiting Analysis",
	"published": "2024-04-08T14:15:07.600",
	"lastModified": "2024-08-21T21:35:05.793",
	"descriptions": [
		{
			"lang": "en",
			"value": "An issue was discovered in OFPMatch in parser.py in Faucet SDN Ryu version 4.34, allows remote attackers to cause a denial of service (DoS) (infinite loop)."
		},
		{
			"lang": "es",
			"value": "Se descubrió un problema en OFPMatch en parser.py en Faucet SDN Ryu versión 4.34, que permite a atacantes remotos provocar una denegación de servicio (DoS) (bucle infinito)."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"url": "https://gist.github.com/ErodedElk/1133d64dde2d92393a065edc9b243792"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://github.com/faucetsdn/ryu/issues/188"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"attackVector": "NETWORK",
					"attackComplexity": "LOW",
					"privilegesRequired": "NONE",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "NONE",
					"availabilityImpact": "HIGH",
					"baseScore": 7.5,
					"baseSeverity": "HIGH"
				},
				"exploitabilityScore": 3.9,
				"impactScore": 3.6
			}
		]
	},
	"weaknesses": [
		{
			"source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
			"type": "Secondary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-835"
				}
			]
		}
	]
}
