{
	"id": "CVE-2024-39329",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Received",
	"published": "2024-07-10T05:15:12.097",
	"lastModified": "2024-07-10T05:15:12.097",
	"descriptions": [
		{
			"lang": "en",
			"value": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. The django.contrib.auth.backends.ModelBackend.authenticate() method allows remote attackers to enumerate users via a timing attack involving login requests for users with an unusable password."
		},
		{
			"lang": "es",
			"value": "Se descubrió un problema en Django 5.0 anterior a 5.0.7 y 4.2 anterior a 4.2.14. El método django.contrib.auth.backends.ModelBackend.authenticate() permite a atacantes remotos enumerar usuarios mediante un ataque de sincronización que involucra solicitudes de inicio de sesión para usuarios con una contraseña inutilizable."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"url": "https://docs.djangoproject.com/en/dev/releases/security/"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://groups.google.com/forum/#%21forum/django-announce"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"
		}
	],
	"metrics": {}
}
