{
	"id": "CVE-2024-5629",
	"sourceIdentifier": "cna@mongodb.com",
	"vulnStatus": "Undergoing Analysis",
	"published": "2024-06-05T15:15:12.737",
	"lastModified": "2024-06-06T14:17:35.017",
	"descriptions": [
		{
			"lang": "en",
			"value": "An out-of-bounds read in the 'bson' module of PyMongo 4.6.2 or earlier allows deserialization of malformed BSON provided by a Server to raise an exception which may contain arbitrary application memory."
		},
		{
			"lang": "es",
			"value": "Una lectura fuera de los límites en el módulo 'bson' de PyMongo 4.6.2 o anterior permite la deserialización de BSON mal formado proporcionado por un servidor para generar una excepción que puede contener memoria de aplicación arbitraria."
		}
	],
	"references": [
		{
			"source": "cna@mongodb.com",
			"url": "https://jira.mongodb.org/browse/PYTHON-4305"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "cna@mongodb.com",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:N/A:L",
					"attackVector": "NETWORK",
					"attackComplexity": "HIGH",
					"privilegesRequired": "NONE",
					"userInteraction": "REQUIRED",
					"scope": "CHANGED",
					"confidentialityImpact": "LOW",
					"integrityImpact": "NONE",
					"availabilityImpact": "LOW",
					"baseScore": 4.7,
					"baseSeverity": "MEDIUM"
				},
				"exploitabilityScore": 1.6,
				"impactScore": 2.7
			}
		]
	},
	"weaknesses": [
		{
			"source": "cna@mongodb.com",
			"type": "Secondary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-125"
				}
			]
		}
	]
}
