{
	"id": "CVE-2024-6595",
	"sourceIdentifier": "cve@gitlab.com",
	"vulnStatus": "Undergoing Analysis",
	"published": "2024-07-17T02:15:10.130",
	"lastModified": "2024-07-17T13:34:20.520",
	"descriptions": [
		{
			"lang": "en",
			"value": "An issue was discovered in GitLab CE/EE affecting all versions starting from 11.8 prior to 16.11.6, starting from 17.0 prior to 17.0.4, and starting from 17.1 prior to 17.1.2 where it was possible to upload an NPM package with conflicting package data."
		},
		{
			"lang": "es",
			"value": "Se descubri√≥ un problema en GitLab CE/EE que afecta a todas las versiones desde la 11.8 anterior a la 16.11.6, desde la 17.0 anterior a la 17.0.4 y desde la 17.1 anterior a la 17.1.2 donde era posible cargar un paquete NPM con conflictos datos del paquete."
		}
	],
	"references": [
		{
			"source": "cve@gitlab.com",
			"url": "https://blog.vlt.sh/blog/the-massive-hole-in-the-npm-ecosystem"
		},
		{
			"source": "cve@gitlab.com",
			"url": "https://gitlab.com/gitlab-org/gitlab/-/issues/417975"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "cve@gitlab.com",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:C/C:N/I:L/A:N",
					"attackVector": "NETWORK",
					"attackComplexity": "HIGH",
					"privilegesRequired": "LOW",
					"userInteraction": "REQUIRED",
					"scope": "CHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "LOW",
					"availabilityImpact": "NONE",
					"baseScore": 3,
					"baseSeverity": "LOW"
				},
				"exploitabilityScore": 1.3,
				"impactScore": 1.4
			}
		]
	},
	"weaknesses": [
		{
			"source": "cve@gitlab.com",
			"type": "Secondary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-427"
				}
			]
		}
	]
}
