{
	"id": "CVE-2024-5130",
	"sourceIdentifier": "security@huntr.dev",
	"vulnStatus": "Received",
	"published": "2024-06-06T19:16:04.813",
	"lastModified": "2024-06-06T19:16:04.813",
	"descriptions": [
		{
			"lang": "en",
			"value": "An Incorrect Authorization vulnerability exists in lunary-ai/lunary versions up to and including 1.2.2, which allows unauthenticated users to delete any dataset. The vulnerability is due to the lack of proper authorization checks in the dataset deletion endpoint. Specifically, the endpoint does not verify if the provided project ID belongs to the current user, thereby allowing any dataset to be deleted without proper authentication. This issue was fixed in version 1.2.8."
		}
	],
	"references": [
		{
			"source": "security@huntr.dev",
			"url": "https://github.com/lunary-ai/lunary/commit/14078c1d2b8766075bf655f187ece24c7a787776"
		},
		{
			"source": "security@huntr.dev",
			"url": "https://huntr.com/bounties/e81a9871-308d-4628-9726-af66643a16fe"
		}
	],
	"metrics": {
		"cvssMetricV30": [
			{
				"source": "security@huntr.dev",
				"type": "Secondary",
				"cvssData": {
					"version": "3.0",
					"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
					"attackVector": "NETWORK",
					"attackComplexity": "LOW",
					"privilegesRequired": "NONE",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "HIGH",
					"availabilityImpact": "NONE",
					"baseScore": 7.5,
					"baseSeverity": "HIGH"
				},
				"exploitabilityScore": 3.9,
				"impactScore": 3.6
			}
		]
	},
	"weaknesses": [
		{
			"source": "security@huntr.dev",
			"type": "Primary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-863"
				}
			]
		}
	]
}
