{
	"id": "CVE-2024-38875",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Awaiting Analysis",
	"published": "2024-07-10T05:15:12.020",
	"lastModified": "2024-07-11T13:05:54.930",
	"descriptions": [
		{
			"lang": "en",
			"value": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets."
		},
		{
			"lang": "es",
			"value": "Se descubrió un problema en Django 4.2 anterior a 4.2.14 y 5.0 anterior a 5.0.7. urlize y urlizetrunc estuvieron sujetos a un posible ataque de denegación de servicio a través de ciertas entradas con una gran cantidad de corchetes."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"url": "https://docs.djangoproject.com/en/dev/releases/security/"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://groups.google.com/forum/#%21forum/django-announce"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"
		}
	],
	"metrics": {}
}
