{
	"id": "CVE-2019-25219",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Received",
	"published": "2024-10-29T17:15:03.567",
	"lastModified": "2024-10-29T17:15:03.567",
	"descriptions": [
		{
			"lang": "en",
			"value": "Asio C++ Library before 1.13.0 lacks a fallback error code in the case of SSL_ERROR_SYSCALL with no associated error information from the SSL library being used."
		},
		{
			"lang": "es",
			"value": "La librería Asio C++ anterior a 1.13.0 carece de un código de error de respaldo en el caso de SSL_ERROR_SYSCALL sin información de error asociada de la librería SSL que se está utilizando."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"url": "https://github.com/chriskohlhoff/asio/commit/93337cba7b013150f5aa6194393e1d94be2853ec"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://github.com/chriskohlhoff/asio/compare/asio-1-12-2...asio-1-13-0"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://think-async.com/Asio/"
		}
	],
	"metrics": {}
}
