{
  "cve": {
    "id": "CVE-2020-26159",
    "sourceIdentifier": "cve@mitre.org",
    "vulnStatus": "Rejected",
    "published": "2020-09-30T21:15:13.357",
    "lastModified": "2023-11-07T03:20:30.767",
    "descriptions": [
      {
        "lang": "en",
        "value": "Rejected reason: DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Further investigation showed that it was not a security issue. Notes: none"
      }
    ],
    "references": [],
    "metrics": {}
  }
}
